"""empty message

Revision ID: a4c085e86792
Revises: fc71374e5a59
Create Date: 2019-09-20 00:50:00.489764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4c085e86792'
down_revision = 'fc71374e5a59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data', sa.Column('timestamp', sa.Time(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('data', 'timestamp')
    # ### end Alembic commands ###
