"""empty message

Revision ID: fc71374e5a59
Revises: 
Create Date: 2019-09-11 17:54:10.202647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc71374e5a59'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('keyword', sa.String(length=50), nullable=True),
    sa.Column('url', sa.String(length=200), nullable=True),
    sa.Column('domain', sa.String(length=100), nullable=True),
    sa.Column('timeload', sa.Integer(), nullable=True),
    sa.Column('code_response', sa.Integer(), nullable=True),
    sa.Column('size_page', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_code_response'), 'data', ['code_response'], unique=False)
    op.create_index(op.f('ix_data_date'), 'data', ['date'], unique=False)
    op.create_index(op.f('ix_data_domain'), 'data', ['domain'], unique=False)
    op.create_index(op.f('ix_data_keyword'), 'data', ['keyword'], unique=False)
    op.create_index(op.f('ix_data_size_page'), 'data', ['size_page'], unique=False)
    op.create_index(op.f('ix_data_timeload'), 'data', ['timeload'], unique=False)
    op.create_index(op.f('ix_data_url'), 'data', ['url'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_data_url'), table_name='data')
    op.drop_index(op.f('ix_data_timeload'), table_name='data')
    op.drop_index(op.f('ix_data_size_page'), table_name='data')
    op.drop_index(op.f('ix_data_keyword'), table_name='data')
    op.drop_index(op.f('ix_data_domain'), table_name='data')
    op.drop_index(op.f('ix_data_date'), table_name='data')
    op.drop_index(op.f('ix_data_code_response'), table_name='data')
    op.drop_table('data')
    # ### end Alembic commands ###
